name = "v22"
description = ""
version = "0.1.0-dev"

authors = ["xav"]
maintainers = ["xav <example@example.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["v22"]

[[depends-on]]
gnatcoll = "^25.0.0"
